Publish API Test results

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -120,5 +120,42 @@ pipeline {
                 }
             }
         }
+        
+        stage('API Tests') {
+            agent {
+                docker {
+                    image 'mcr.microsoft.com/playwright:v1.50.0-jammy'
+                    reuseNode true
+                    args '-u 0 --network=host'
+                }
+            }
+
+            steps {
+                dir('test-api') {
+                    sh """
+                        if [ ! -f package.json ]; then
+                        echo "ERROR: package.json not found in test-api"
+                        exit 1
+                        fi
+
+                        npm install
+                        npx playwright test --reporter=junit,html
+                    """
+                }
+            }
+
+            post {
+                always {
+                    junit allowEmptyResults: true, testResults: 'test-api/results.xml'
+
+                    publishHTML(target: [
+                        reportDir: 'test-api/playwright-report',
+                        reportFiles: 'index.html',
+                        reportName: 'Playwright API Test Report'
+                    ])
+                }
+            }
+        }
+
     }
 }
